modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="kindlyrecipes"
version="1.0.0"
displayName="KindlyKlan Recipes Blocker"
displayURL="https://discord.gg/kindlyklan"
credits="Utilities para KindlyKlan"
authors="Javivi"

# Start of user code block mod configurations
# End of user code block mod configuration

[[dependencies.kindlyrecipes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"
